FRAC_SOURCES	:= app/app_handler.c \
				   app/event/event.c \
				   app/event/key_event/key_event.c \
				   app/event/key_event/newton_key_event.c \
				   complexes/complex_number.c \
				   complexes/complex_init.c \
				   main/main.c \
				   main/input_parsing.c \
				   main/error.c \
				   main/init_func.c \
				   fractal/julia.c \
				   fractal/draw_fractal.c \
				   fractal/pointer_functions.c \
				   polynomes/create_polynome.c \
				   polynomes/derivative_calc.c \
				   polynomes/compute_cubic_root/cubic_root_calc.c \
				   polynomes/compute_cubic_root/simple_calc.c \
				   newton/newton_fractal.c \
				   newton/distance_eval.c \
				   newton/draw_functions.c \
				   normalize.c \
				   utils/ft_memcmp.c \
				   utils/ft_strlen.c \
				   utils/ft_memset.c \
				   utils/ft_strncmp.c \
				   utils/ft_atof.c \
				   utils/ft_isdigit.c \
				   utils/power.c \
				   utils/ft_atoi.c \
				   utils/ft_strchr.c \
